[book]
authors = ["blackanger"]
language = "zh_CN"
multilingual = false
src = "src"
title = "rust-magazine"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
theme = "mytheme"
default-theme = "rust"
google-analytics = "UA-188947685-1"
git-repository-url = "https://github.com/RustMagazine/rust_magazine_2021"
additional-js = ["mermaid.min.js", "mermaid-init.js"]


[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = true
level = 2


